import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
        {/* bg-rendang-900 */}
        {/* Logo Rendang Ponky  

          Kontak: "Hubungi kami di WhatsApp: 0812-xxx-xxxx"  

          Ikon media sosial (Instagram, Facebook)  

          "© 2025 Rendang Ponky – Kelezatan Tradisi dalam Setiap Gigitan"

          Tujuan: Memberikan informasi kontak dan memperkuat branding.  

          Tips: Jaga desain simpel dan bersih agar tidak mengalihkan perhatian dari CTA utama.
        */}

      </body>
    </html>
  );
}
